### ISSUE TITLE
TEC Help Link to gather user feedback

### ISSUE THREAD

**Issue by GriffGreen** [TECommons/tec-interface#4]
## 📋   Anything to add?

We would love to collect feedback from the users, and the best place to put the feedback form is right on the website! There are a lot of steps here...

## 🎉   Subtasks

- [x] Find a Champion to take this issue on and see it to completion
- [ ] Get feedback on this idea from @sembrestels and the Tech Spec team
- [ ] Create a type form to gather the feedback we want @Manu
- [ ] Decide where to put it on the various screens... @markoprljic @Fiorella
- [ ] Launch it on all of our screens!

## 🤼‍♂️   Reviewer

@GriffGreen

**Comment by GriffGreen** [comment]
Aragon was using a service worth researching... it was in the Aragon Client

**Comment by markoprljic** [comment]
> Aragon was using a service worth researching... it was in the Aragon Client

I think they're using https://www.helpscout.com/
